version: "3"

services:

  runtime-setup:
    image: swift-certificates:22.04-5.9
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.9-jammy"

  test:
    image: swift-certificates:22.04-5.9
    environment:
      - WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error
      - MAX_ALLOCS_ALLOWED_tiny_array_cow_append_contents_of=3
      - MAX_ALLOCS_ALLOWED_tiny_array_non_allocating_operations=0
      # - SANITIZER_ARG=--sanitize=thread # TSan broken still

  shell:
    image: swift-certificates:22.04-5.9
