version: "3"

services:

  runtime-setup:
    image: swift-certificates:22.04-5.9
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.9-jammy"

  test:
    image: swift-certificates:22.04-5.9
    environment:
      - WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error
      - MAX_ALLOCS_ALLOWED_parse_webpki_roots=779
      # - SANITIZER_ARG=--sanitize=thread # TSan broken still

  shell:
    image: swift-certificates:22.04-5.9
