version: "3"

services:

  runtime-setup:
    image: swift-certificates:22.04-5.8
    build:
      args:
        ubuntu_version: "jammy"
        swift_version: "5.8"

  test:
    image: swift-certificates:22.04-5.8
    environment:
      - WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error
      - MAX_ALLOCS_ALLOWED_1=0
      - MAX_ALLOCS_ALLOWED_2=0
      - MAX_ALLOCS_ALLOWED_3=0
      # - SANITIZER_ARG=--sanitize=thread # TSan broken still

  shell:
    image: swift-certificates:22.04-5.8
