version: "3"

services:

  runtime-setup:
    image: swift-certificates:22.04-main
    build:
      args:
        base_image: "swiftlang/swift:nightly-main-jammy"

  test:
    image: swift-certificates:22.04-main
    environment:
      - SWIFT_VERSION=main
      - WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error
      # - SANITIZER_ARG=--sanitize=thread # TSan broken still

  shell:
    image: swift-certificates:22.04-main
    
  update-benchmark-baseline:
    image: swift-certificates:22.04-main
    environment:
      - SWIFT_VERSION=main
