version: "3"

services:

  runtime-setup:
    image: swift-certificates:22.04-5.10
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.10-jammy"

  test:
    image: swift-certificates:22.04-5.10
    environment:
      - SWIFT_VERSION=5.10
      - WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error
      # - SANITIZER_ARG=--sanitize=thread # TSan broken still

  shell:
    image: swift-certificates:22.04-5.10

  update-benchmark-baseline:
    image: swift-certificates:22.04-5.10
    environment:
      - SWIFT_VERSION=5.10
